# top level stuff you probably don't need to touch
highlighter: rouge
#markdown: rdiscount
#rdiscount:
#  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://gauravbisen.com/
baseurl: 
name: Gaurav Bisen
title: Gaurav Singh Bisen
author: Gaurav Singh Bisen
description: Personal blog and resume
avatar: profile.jpg
email: bisen.gaurav23@gmail.com
github: gauravsinghbisen # username
twitter: midspectrum
linkedin: gauravsinghbisen
medium: gauravsinghbisen
facebook: gauravsinghbisen
instagram: midspectrum
#Comment out if you don't want disqus
#disqus: username
google_analytics: UA-71475870-2


# needed for travis-ci build
exclude: [vendor]
